### ISSUE TITLE
Rename SuperDirt effect parameters

### ISSUE THREAD

**Issue by rapofran** [xi-livecode/xi-superdirt#2]
For example, `cutoff` should be renamed to `lpf` (same as in TidalCycles), `resonance` to `lpq`, etc.

**Comment by munshkr** [comment]
I suggest to make a list of all parameters here first, by checking Tidal source code.

**Comment by munshkr** [comment]
Fixed on 58a3cde32d45285883f3f6875deaffe84146218d
